### ISSUE TITLE
オーガナイザーチームを作る

### ISSUE THREAD

**Issue by hsbt** [asakusarb/oedo05#2]
- オーガナイザー( @ko1 )
- 会計( @hsbt )
- リポート係

**Comment by ko1** [comment]
report かがりは、別途募集する。

**Comment by kakutani** [comment]
地域Ruby会議界隈では"実行委員長"っていうロール名になってます。こんかいはよろしくお願いします！ > @ko1

**Comment by hsbt** [comment]
@ko1 さんが何かを決めてお金回りは僕が頑張る。って感じでいく。
